import { Component } from '../types';

export function serializeCircuit(components: Component[]): string {
  let netlist = '* Generated by CircuitFlow\n';
  components.forEach(c => {
    netlist += `${c.id} ${c.nodeA} ${c.nodeB} ${c.originalValue}\n`;
  });
  return netlist;
}
