import { Component } from '../types';

export function serializeCircuit(components: Component[]): string {
  let netlist = '* Generated by CircuitFlow\n';
  
  components.forEach(c => {
    const val = c.type === 'W' ? '' : c.originalValue;
    const nodeC = c.nodeC ? ` ${c.nodeC}` : '';
    const extra = (c.type === 'V' || c.type === 'I') && c.phase !== undefined 
      ? ` ${c.phase}` 
      : (c.type === 'Q' && c.beta !== undefined ? ` ${c.beta}` : '');
    
    netlist += `${c.id} ${c.nodeA} ${c.nodeB}${nodeC} ${val}${extra}\n`.trim() + '\n';
  });

  netlist += '\n* Position Metadata\n';
  components.forEach(c => {
    if (c.position) {
      const { x1, y1, x2, y2, x3, y3 } = c.position;
      let posStr = `# pos ${c.id} ${x1} ${y1} ${x2} ${y2}`;
      if (x3 !== undefined && y3 !== undefined) {
        posStr += ` ${x3} ${y3}`;
      }
      netlist += posStr + '\n';
    }
  });

  return netlist;
}
