import { Component } from '../types';

export function serializeCircuit(components: Component[]): string {
  let netlist = '* Generated by CircuitFlow\n';
  
  // First pass: Components
  components.forEach(c => {
    const val = c.type === 'W' ? '' : c.originalValue;
    netlist += `${c.id} ${c.nodeA} ${c.nodeB} ${val}\n`.trim() + '\n';
  });

  netlist += '\n* Position Metadata\n';
  // Second pass: Positions
  components.forEach(c => {
    if (c.position) {
      const { x1, y1, x2, y2 } = c.position;
      netlist += `# pos ${c.id} ${x1} ${y1} ${x2} ${y2}\n`;
    }
  });

  return netlist;
}
